name: ima

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    networks:
      - internal_network
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']

  valkey:
    image: valkey/valkey:8.0
    restart: always
    ports:
      - 6379:6379
    networks:
      - internal_network
    volumes:
      - valkey:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
      - 5172:5172
    networks:
      - internal_network
      - external_network
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres
      - REDIS_HOST=valkey
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'if [ "$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:5172)" -ne 426 ]; then exit 1; fi'
      retries: 10
      interval: 1s
    depends_on:
      - postgres
      - valkey

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    restart: unless-stopped
    ports:
      - 5173:80
    networks:
      - external_network
    depends_on:
      server:
        condition: service_healthy

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  postgres:
  valkey:
