name: Report

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [server]
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    steps:
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          artifact: ${{ matrix.workspace }}
          name: ${{ matrix.workspace }}
          path: ${{ matrix.workspace }}/junit.xml
          reporter: jest-junit
